name: Self-Hosted Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo "This is a multi-line script!"
        echo "It can run any commands you need."
    - name: Run a command
      run: echo "This is a single-line command."